/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package universidadg8.vistas;

import static universidadg8.UniversidadG8.adata;
import static universidadg8.UniversidadG8.listaAlumnos;
import universidadg8.entidades.Alumno;

/**
 *
 * @author tcnlu
 */
public class JPBorrarAlumno extends javax.swing.JPanel {

    /**
     * Creates new form JPBorrarAlumno
     */
    private void actualizarLista() {
        listaAlumnos = adata.obtenerAlumnos();
        jcbAlumnosBorrarAlumno.removeAllItems();
        for (Alumno alumnos : listaAlumnos) {
            jcbAlumnosBorrarAlumno.addItem(alumnos.getNombre() + " " + alumnos.getApellido());
        }
    }

    public JPBorrarAlumno() {
        initComponents();
        actualizarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTituloBorrarAlumno = new javax.swing.JLabel();
        jcbAlumnosBorrarAlumno = new javax.swing.JComboBox<>();
        jlFechaActualizarAlumno = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtfNombreBorrarAlumno = new javax.swing.JTextField();
        jtfApeBorrarAlumno = new javax.swing.JTextField();
        jtfDNIBorrarAlumno = new javax.swing.JTextField();
        jlTitulo2BorrarAlumno = new javax.swing.JLabel();
        jtfFechaNacBorrarAlumno = new javax.swing.JTextField();
        jlNomActualizarAlumno = new javax.swing.JLabel();
        jlApeActualizarAlumno = new javax.swing.JLabel();
        jlDNIActualizarAlumno = new javax.swing.JLabel();
        jtfIDAlumBorrarAlumno = new javax.swing.JTextField();
        jbBorrarBorrarAlumno = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Borrar Alumno"));

        jlTituloBorrarAlumno.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jlTituloBorrarAlumno.setText("Borrar Alumno");

        jcbAlumnosBorrarAlumno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbAlumnosBorrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAlumnosBorrarAlumnoActionPerformed(evt);
            }
        });

        jlFechaActualizarAlumno.setText("Fecha Nacimiento");

        jLabel1.setText("Legajo");

        jtfNombreBorrarAlumno.setEditable(false);

        jtfApeBorrarAlumno.setEditable(false);

        jtfDNIBorrarAlumno.setEditable(false);
        jtfDNIBorrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDNIBorrarAlumnoActionPerformed(evt);
            }
        });

        jlTitulo2BorrarAlumno.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jlTitulo2BorrarAlumno.setText("Datos");

        jtfFechaNacBorrarAlumno.setEditable(false);

        jlNomActualizarAlumno.setText("Nombre");

        jlApeActualizarAlumno.setText("Apellido");

        jlDNIActualizarAlumno.setText("DNI");

        jtfIDAlumBorrarAlumno.setEditable(false);

        jbBorrarBorrarAlumno.setText("Borrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbBorrarBorrarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlTitulo2BorrarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNomActualizarAlumno)
                            .addComponent(jlFechaActualizarAlumno)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlDNIActualizarAlumno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlApeActualizarAlumno, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfApeBorrarAlumno, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfDNIBorrarAlumno, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfFechaNacBorrarAlumno, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfNombreBorrarAlumno, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfIDAlumBorrarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlTituloBorrarAlumno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcbAlumnosBorrarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTituloBorrarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbAlumnosBorrarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jlTitulo2BorrarAlumno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomActualizarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNombreBorrarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlApeActualizarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfApeBorrarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDNIActualizarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDNIBorrarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfIDAlumBorrarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlFechaActualizarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfFechaNacBorrarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbBorrarBorrarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcbAlumnosBorrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAlumnosBorrarAlumnoActionPerformed
        if (jcbAlumnosBorrarAlumno.getSelectedIndex() >= 0) {
            jtfNombreBorrarAlumno.setText(listaAlumnos.get(jcbAlumnosBorrarAlumno.getSelectedIndex()).getNombre());
            jtfApeBorrarAlumno.setText(listaAlumnos.get(jcbAlumnosBorrarAlumno.getSelectedIndex()).getApellido());
            jtfDNIBorrarAlumno.setText(String.valueOf(listaAlumnos.get(jcbAlumnosBorrarAlumno.getSelectedIndex()).getDni()));
            jtfIDAlumBorrarAlumno.setText(String.valueOf(listaAlumnos.get(jcbAlumnosBorrarAlumno.getSelectedIndex()).getId_alumno()));
            jtfFechaNacBorrarAlumno.setText(String.valueOf(listaAlumnos.get(jcbAlumnosBorrarAlumno.getSelectedIndex()).getFecha_nacimiento()));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbAlumnosBorrarAlumnoActionPerformed

    private void jtfDNIBorrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDNIBorrarAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDNIBorrarAlumnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbBorrarBorrarAlumno;
    private javax.swing.JComboBox<String> jcbAlumnosBorrarAlumno;
    private javax.swing.JLabel jlApeActualizarAlumno;
    private javax.swing.JLabel jlDNIActualizarAlumno;
    private javax.swing.JLabel jlFechaActualizarAlumno;
    private javax.swing.JLabel jlNomActualizarAlumno;
    private javax.swing.JLabel jlTitulo2BorrarAlumno;
    private javax.swing.JLabel jlTituloBorrarAlumno;
    private javax.swing.JTextField jtfApeBorrarAlumno;
    private javax.swing.JTextField jtfDNIBorrarAlumno;
    private javax.swing.JTextField jtfFechaNacBorrarAlumno;
    private javax.swing.JTextField jtfIDAlumBorrarAlumno;
    private javax.swing.JTextField jtfNombreBorrarAlumno;
    // End of variables declaration//GEN-END:variables
}
